services:
  webserver:
    container_name: webserver
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./html:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
  mysql:
      container_name: mysql
      image: mysql:8.0
      restart: always
      volumes:
        - ./sql:/docker-entrypoint-initdb.d
        - db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "example"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "user"
      ports:
        - "3306:3306"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      environment:
        PMA_HOST: mysql
      ports:
        - "8080:80"
volumes:
  db: